[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wiretap"
version = "1.0.10"
requires-python = ">=3.10.5"
authors = [{ name = "he-dev" }]




