[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wiretap"
version = "3.0.1"
requires-python = ">=3.10"
authors = [{ name = "he-dev" }]

[project.urls]
"GitHub" = "https://github.com/he-dev/wiretap-py"



